In [1]:
import pandas as pd
import joblib

In [2]:
import joblib
model = joblib.load("risk_model.pkl")

In [3]:
print(type(model))

<class 'sklearn.ensemble._gb.GradientBoostingClassifier'>

In [5]:
import pandas as pd

X_final = pd.read_csv("../data/processed/X_final.csv")

final_features = X_final.columns.tolist()

final_features

['Crop_Year',
 'Area',
 'Year',
 'AverageTemperature',
 'State_Name_Andhra Pradesh',
 'State_Name_Arunachal Pradesh',
 'State_Name_Assam',
 'State_Name_Bihar',
 'State_Name_Chandigarh',
 'State_Name_Chhattisgarh',
 'State_Name_Dadra and Nagar Haveli',
 'State_Name_Goa',
 'State_Name_Gujarat',
 'State_Name_Haryana',
 'State_Name_Himachal Pradesh',
 'State_Name_Jammu and Kashmir ',
 'State_Name_Jharkhand',
 'State_Name_Karnataka',
 'State_Name_Kerala',
 'State_Name_Madhya Pradesh',
 'State_Name_Maharashtra',
 'State_Name_Manipur',
 'State_Name_Meghalaya',
 'State_Name_Mizoram',
 'State_Name_Nagaland',
 'State_Name_Odisha',
 'State_Name_Puducherry',
 'State_Name_Punjab',
 'State_Name_Rajasthan',
 'State_Name_Sikkim',
 'State_Name_Tamil Nadu',
 'State_Name_Telangana ',
 'State_Name_Tripura',
 'State_Name_Uttar Pradesh',
 'State_Name_Uttarakhand',
 'State_Name_West Bengal',
 'Season_Kharif     ',
 'Season_Rabi       ',
 'Season_Summer     ',
 'Season_Whole Year ',
 'Season_Winter     ',
 'Crop_Arcanut (Processed)',
 'Crop_Arecanut',
 'Crop_Arhar/Tur',
 'Crop_Ash Gourd',
 'Crop_Atcanut (Raw)',
 'Crop_Bajra',
 'Crop_Banana',
 'Crop_Barley',
 'Crop_Bean',
 'Crop_Beans & Mutter(Vegetable)',
 'Crop_Beet Root',
 'Crop_Ber',
 'Crop_Bhindi',
 'Crop_Bitter Gourd',
 'Crop_Black pepper',
 'Crop_Blackgram',
 'Crop_Bottle Gourd',
 'Crop_Brinjal',
 'Crop_Cabbage',
 'Crop_Cardamom',
 'Crop_Carrot',
 'Crop_Cashewnut',
 'Crop_Cashewnut Processed',
 'Crop_Cashewnut Raw',
 'Crop_Castor seed',
 'Crop_Cauliflower',
 'Crop_Citrus Fruit',
 'Crop_Coconut ',
 'Crop_Coffee',
 'Crop_Colocosia',
 'Crop_Cond-spcs other',
 'Crop_Coriander',
 'Crop_Cotton(lint)',
 'Crop_Cowpea(Lobia)',
 'Crop_Cucumber',
 'Crop_Drum Stick',
 'Crop_Dry chillies',
 'Crop_Dry ginger',
 'Crop_Garlic',
 'Crop_Ginger',
 'Crop_Gram',
 'Crop_Grapes',
 'Crop_Groundnut',
 'Crop_Guar seed',
 'Crop_Horse-gram',
 'Crop_Jack Fruit',
 'Crop_Jobster',
 'Crop_Jowar',
 'Crop_Jute',
 'Crop_Jute & mesta',
 'Crop_Kapas',
 'Crop_Khesari',
 'Crop_Korra',
 'Crop_Lab-Lab',
 'Crop_Lemon',
 'Crop_Lentil',
 'Crop_Linseed',
 'Crop_Litchi',
 'Crop_Maize',
 'Crop_Mango',
 'Crop_Masoor',
 'Crop_Mesta',
 'Crop_Moong(Green Gram)',
 'Crop_Moth',
 'Crop_Niger seed',
 'Crop_Oilseeds total',
 'Crop_Onion',
 'Crop_Orange',
 'Crop_Other  Rabi pulses',
 'Crop_Other Cereals & Millets',
 'Crop_Other Citrus Fruit',
 'Crop_Other Fresh Fruits',
 'Crop_Other Kharif pulses',
 'Crop_Other Vegetables',
 'Crop_Paddy',
 'Crop_Papaya',
 'Crop_Pear',
 'Crop_Peas  (vegetable)',
 'Crop_Peas & beans (Pulses)',
 'Crop_Perilla',
 'Crop_Pineapple',
 'Crop_Plums',
 'Crop_Pome Fruit',
 'Crop_Pome Granet',
 'Crop_Potato',
 'Crop_Pulses total',
 'Crop_Pump Kin',
 'Crop_Ragi',
 'Crop_Rajmash Kholar',
 'Crop_Rapeseed &Mustard',
 'Crop_Redish',
 'Crop_Ribed Guard',
 'Crop_Rice',
 'Crop_Ricebean (nagadal)',
 'Crop_Rubber',
 'Crop_Safflower',
 'Crop_Samai',
 'Crop_Sannhamp',
 'Crop_Sapota',
 'Crop_Sesamum',
 'Crop_Small millets',
 'Crop_Snak Guard',
 'Crop_Soyabean',
 'Crop_Sugarcane',
 'Crop_Sunflower',
 'Crop_Sweet potato',
 'Crop_Tapioca',
 'Crop_Tea',
 'Crop_Tobacco',
 'Crop_Tomato',
 'Crop_Total foodgrain',
 'Crop_Turmeric',
 'Crop_Turnip',
 'Crop_Urad',
 'Crop_Varagu',
 'Crop_Water Melon',
 'Crop_Wheat',
 'Crop_Yam',
 'Crop_other fibres',
 'Crop_other misc. pulses',
 'Crop_other oilseeds']

In [6]:
import joblib
model = joblib.load("risk_model.pkl")

In [7]:
len(final_features)

162

In [8]:
import numpy as np

# create template with zeros
template = np.zeros(len(final_features))

template

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
scenarios = pd.DataFrame([
    template.copy(),
    template.copy(),
    template.copy()
], columns=final_features)

scenarios.index = ["Ideal", "Moderate", "Extreme"]

In [10]:
print(final_features)

['Crop_Year', 'Area', 'Year', 'AverageTemperature', 'State_Name_Andhra Pradesh', 'State_Name_Arunachal Pradesh', 'State_Name_Assam', 'State_Name_Bihar', 'State_Name_Chandigarh', 'State_Name_Chhattisgarh', 'State_Name_Dadra and Nagar Haveli', 'State_Name_Goa', 'State_Name_Gujarat', 'State_Name_Haryana', 'State_Name_Himachal Pradesh', 'State_Name_Jammu and Kashmir ', 'State_Name_Jharkhand', 'State_Name_Karnataka', 'State_Name_Kerala', 'State_Name_Madhya Pradesh', 'State_Name_Maharashtra', 'State_Name_Manipur', 'State_Name_Meghalaya', 'State_Name_Mizoram', 'State_Name_Nagaland', 'State_Name_Odisha', 'State_Name_Puducherry', 'State_Name_Punjab', 'State_Name_Rajasthan', 'State_Name_Sikkim', 'State_Name_Tamil Nadu', 'State_Name_Telangana ', 'State_Name_Tripura', 'State_Name_Uttar Pradesh', 'State_Name_Uttarakhand', 'State_Name_West Bengal', 'Season_Kharif     ', 'Season_Rabi       ', 'Season_Summer     ', 'Season_Whole Year ', 'Season_Winter     ', 'Crop_Arcanut (Processed)', 'Crop_Arecanut', 'Crop_Arhar/Tur', 'Crop_Ash Gourd', 'Crop_Atcanut (Raw)', 'Crop_Bajra', 'Crop_Banana', 'Crop_Barley', 'Crop_Bean', 'Crop_Beans & Mutter(Vegetable)', 'Crop_Beet Root', 'Crop_Ber', 'Crop_Bhindi', 'Crop_Bitter Gourd', 'Crop_Black pepper', 'Crop_Blackgram', 'Crop_Bottle Gourd', 'Crop_Brinjal', 'Crop_Cabbage', 'Crop_Cardamom', 'Crop_Carrot', 'Crop_Cashewnut', 'Crop_Cashewnut Processed', 'Crop_Cashewnut Raw', 'Crop_Castor seed', 'Crop_Cauliflower', 'Crop_Citrus Fruit', 'Crop_Coconut ', 'Crop_Coffee', 'Crop_Colocosia', 'Crop_Cond-spcs other', 'Crop_Coriander', 'Crop_Cotton(lint)', 'Crop_Cowpea(Lobia)', 'Crop_Cucumber', 'Crop_Drum Stick', 'Crop_Dry chillies', 'Crop_Dry ginger', 'Crop_Garlic', 'Crop_Ginger', 'Crop_Gram', 'Crop_Grapes', 'Crop_Groundnut', 'Crop_Guar seed', 'Crop_Horse-gram', 'Crop_Jack Fruit', 'Crop_Jobster', 'Crop_Jowar', 'Crop_Jute', 'Crop_Jute & mesta', 'Crop_Kapas', 'Crop_Khesari', 'Crop_Korra', 'Crop_Lab-Lab', 'Crop_Lemon', 'Crop_Lentil', 'Crop_Linseed', 'Crop_Litchi', 'Crop_Maize', 'Crop_Mango', 'Crop_Masoor', 'Crop_Mesta', 'Crop_Moong(Green Gram)', 'Crop_Moth', 'Crop_Niger seed', 'Crop_Oilseeds total', 'Crop_Onion', 'Crop_Orange', 'Crop_Other  Rabi pulses', 'Crop_Other Cereals & Millets', 'Crop_Other Citrus Fruit', 'Crop_Other Fresh Fruits', 'Crop_Other Kharif pulses', 'Crop_Other Vegetables', 'Crop_Paddy', 'Crop_Papaya', 'Crop_Pear', 'Crop_Peas  (vegetable)', 'Crop_Peas & beans (Pulses)', 'Crop_Perilla', 'Crop_Pineapple', 'Crop_Plums', 'Crop_Pome Fruit', 'Crop_Pome Granet', 'Crop_Potato', 'Crop_Pulses total', 'Crop_Pump Kin', 'Crop_Ragi', 'Crop_Rajmash Kholar', 'Crop_Rapeseed &Mustard', 'Crop_Redish', 'Crop_Ribed Guard', 'Crop_Rice', 'Crop_Ricebean (nagadal)', 'Crop_Rubber', 'Crop_Safflower', 'Crop_Samai', 'Crop_Sannhamp', 'Crop_Sapota', 'Crop_Sesamum', 'Crop_Small millets', 'Crop_Snak Guard', 'Crop_Soyabean', 'Crop_Sugarcane', 'Crop_Sunflower', 'Crop_Sweet potato', 'Crop_Tapioca', 'Crop_Tea', 'Crop_Tobacco', 'Crop_Tomato', 'Crop_Total foodgrain', 'Crop_Turmeric', 'Crop_Turnip', 'Crop_Urad', 'Crop_Varagu', 'Crop_Water Melon', 'Crop_Wheat', 'Crop_Yam', 'Crop_other fibres', 'Crop_other misc. pulses', 'Crop_other oilseeds']

In [11]:
def assign_risk_zone(score):
    if score <= 30:
        return "Low"
    elif score <= 60:
        return "Moderate"
    elif score <= 80:
        return "High"
    else:
        return "Critical"

scenarios["Risk Score"] = model.predict_proba(scenarios)[:,1] * 100
scenarios["Risk Zone"] = scenarios["Risk Score"].apply(assign_risk_zone)

scenarios

,Crop_Year,Area,Year,AverageTemperature,State_Name_Andhra Pradesh,State_Name_Arunachal Pradesh,State_Name_Assam,State_Name_Bihar,State_Name_Chandigarh,State_Name_Chhattisgarh,...,Crop_Urad,Crop_Varagu,Crop_Water Melon,Crop_Wheat,Crop_Yam,Crop_other fibres,Crop_other misc. pulses,Crop_other oilseeds,Risk Score,Risk Zone
Ideal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.639516,Moderate
Moderate,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.639516,Moderate
Extreme,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.639516,Moderate

In [12]:
# IDEAL CONDITIONS
scenarios.loc["Ideal", ["AverageTemperature","Area"]] = [22, 1.0]

# MODERATE
scenarios.loc["Moderate", ["AverageTemperature","Area"]] = [30, 1.2]

# EXTREME
scenarios.loc["Extreme", ["AverageTemperature","Area"]] = [38, 1.5]

In [13]:
scenarios["State_Name_Tamil Nadu"] = 0
scenarios.loc[:, "State_Name_Tamil Nadu"] = 1

In [14]:
scenarios["Crop_Paddy"] = 0
scenarios.loc[:, "Crop_Paddy"] = 1

In [15]:
scenarios["Season_Kharif"] = 0
scenarios.loc[:, "Season_Kharif"] = 1

In [17]:
scenarios = scenarios[final_features]

In [18]:
[c for c in final_features if "Season" in c]

['Season_Kharif     ',
 'Season_Rabi       ',
 'Season_Summer     ',
 'Season_Whole Year ',
 'Season_Winter     ']

In [22]:
scenarios = pd.DataFrame([template, template, template], columns=final_features)
scenarios.index = ["Ideal","Moderate","Extreme"]

In [23]:
[c for c in final_features if "Season_" in c]

['Season_Kharif     ',
 'Season_Rabi       ',
 'Season_Summer     ',
 'Season_Whole Year ',
 'Season_Winter     ']

In [20]:
print(scenarios.shape)
print(len(final_features))

(3, 163)
162

In [39]:
scenarios = scenarios[final_features]

In [25]:
scenarios["Crop_Paddy"] = 1
scenarios["State_Name_Tamil Nadu"] = 1

In [30]:
scenarios.loc["Ideal", "Area"] = 1.0
scenarios.loc["Moderate", "Area"] = 1.5
scenarios.loc["Extreme", "Area"] = 2.5

In [31]:
scenarios = scenarios[final_features]

In [33]:
scenarios.loc["Ideal", "Year"] = 2015
scenarios.loc["Moderate", "Year"] = 2018
scenarios.loc["Extreme", "Year"] = 2022

In [34]:
scenarios.loc["Ideal", "AverageTemperature"] = 22
scenarios.loc["Moderate", "AverageTemperature"] = 30
scenarios.loc["Extreme", "AverageTemperature"] = 38

In [35]:
scenarios.loc[:, "Crop_Paddy"] = 0
scenarios.loc[:, "Crop_Tomato"] = 1

In [40]:
risk_scores = model.predict_proba(scenarios)[:,1] * 100

scenarios["Risk Score"] = risk_scores
scenarios["Risk Zone"] = scenarios["Risk Score"].apply(assign_risk_zone)

scenarios[["Risk Score","Risk Zone"]]

/var/folders/mn/g7ny59sx0l3dflgstq12x5pr0000gn/T/ipykernel_15244/1180126566.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  scenarios["Risk Score"] = risk_scores

          Risk Score Risk Zone
Ideal      60.611323      High
Moderate   43.981650  Moderate
Extreme    37.888969  Moderate

In [41]:
def mitigation_recommendation(row):
    if row["Risk Score"] > 80:
        return "Immediate cold storage & emergency dispatch"
    elif row["Risk Score"] > 60:
        return "Priority routing and temperature-controlled storage"
    elif row["Risk Score"] > 30:
        return "Monitor logistics and optimize transport time"
    else:
        return "Standard handling procedures"

scenarios["Recommended Action"] = scenarios.apply(mitigation_recommendation, axis=1)

scenarios[["Risk Score","Risk Zone","Recommended Action"]]

,Risk Score,Risk Zone,Recommended Action
Ideal,60.611323,High,Priority routing and temperature-controlled st...
Moderate,43.981650,Moderate,Monitor logistics and optimize transport time
Extreme,37.888969,Moderate,Monitor logistics and optimize transport time